#!/usr/bin/env bash

# Helper script to write out an inventory file for Ansible.

if [[ -z $MERKLEDB_MONITOR_HOST ]]; then
    echo "Missing required MERKLEDB_MONITOR_HOST env var"
    exit 1
fi

cat > inventory.ini <<EOF
[support]
monitor ansible_ssh_user=ubuntu ansible_host=$MERKLEDB_MONITOR_HOST
EOF
