version: 2
jobs:
  build:
    working_directory: ~/merkle-db
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      JVM_OPTS: -Xmx3200m
      LEIN_ROOT: nbd
    steps:
      - checkout
      - restore_cache:
          keys:
            - merkle-db-{{ checksum "project.clj" }}
            - merkle-db-
      - run: lein monolith each do clean, check, install
      - save_cache:
          paths:
            - ~/.m2
          key: merkle-db-{{ checksum "project.clj" }}
      - run: lein monolith each test
      - run: lein test
      - run: lein coverage --codecov
      - store_artifacts:
          path: target/coverage
          destination: coverage
      - run:
          name: Publish Coverage
          command: "(curl -s https://codecov.io/bash > codecov) && bash codecov -f target/coverage/codecov.json"
