---
- name: Add signing key for Grafana repo
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: Add Grafana package repo
  apt_repository:
    repo: 'deb https://packagecloud.io/grafana/stable/debian/ stretch main'
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: true

- name: Prepare data directory
  file:
    path: "{{ grafana_data_dir }}"
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'

- name: Write Grafana configuration
  template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart grafana

- name: Provision InfluxDB data source
  template:
    src: influxdb-datasource.yaml
    dest: /etc/grafana/provisioning/datasources/influxdb.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart grafana

- name: Provision dashboard source
  template:
    src: dashboard-source.yaml
    dest: /etc/grafana/provisioning/dashboards/file.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart grafana

- name: Sync dashboard configs
  synchronize:
    src: roles/grafana/files/dashboards/
    dest: "{{ grafana_data_dir }}/dashboards"

- name: Start Grafana
  service:
    name: grafana-server
    state: started
