#!/usr/bin/env bash

set -e

if [[ -z $1 ]]; then
    echo "Usage: $(basename $0) <s3-jar-url>"
    exit 1
fi

echo "Downloading Riemann JVM profiler..."
aws s3 cp $1 /tmp/riemann-jvm-profiler.jar
sudo chown root:root /tmp/riemann-jvm-profiler.jar
sudo mv /tmp/riemann-jvm-profiler.jar /var/lib/
