#!/usr/bin/env bash

set -e

if [[ -z $1 || -z $2 ]]; then
    echo "Usage: $(basename $0) <version> <riemann-addr>"
    exit 1
fi

SOLANUM_VERSION=$1
RIEMANN_ADDR=$2

# TODO: from s3://elasticmapreduce/bootstrap-actions/run-if
echo "Instance data:"
cat /mnt/var/lib/info/instance.json

SOLANUM_RELEASE="https://github.com/greglook/solanum/releases/download/${SOLANUM_VERSION}"
SOLANUM_FILE="solanum_${SOLANUM_VERSION}_linux.tar.gz"

echo "Fetching Solanum ${SOLANUM_VERSION}"
wget "${SOLANUM_RELEASE}/${SOLANUM_FILE}" -O "/tmp/${SOLANUM_FILE}"

echo "Installing Solanum..."
tar -xvzf "/tmp/${SOLANUM_FILE}" -C /tmp/
sudo chown root:root /tmp/solanum
sudo mv /tmp/solanum /usr/local/bin/solanum

echo "Configuring sources..."
sudo mkdir /etc/solanum
sudo tee /etc/solanum/config.yml > /dev/null <<EOF
defaults:
  ttl: 180
  tags:
    - solanum

sources:
  - type: cpu
  - type: load
  - type: memory
  - type: network
  - type: disk-space
  - type: disk-stats

outputs:
  - type: riemann
    host: ${RIEMANN_ADDR}
    port: 5555
EOF

echo "Configuring upstart service..."
sudo tee /etc/init/solanum.conf > /dev/null <<EOF
start on startup
setuid daemon
exec /usr/local/bin/solanum /etc/solanum/*
respawn
EOF

echo "Starting service..."
sudo service solanum start
