---
- name: Write tunnel systemd unit
  template:
    src: cluster-tunnel.service
    dest: /etc/systemd/system/cluster-tunnel.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart tunnel

- name: Start tunnel
  systemd:
    name: cluster-tunnel
    daemon_reload: true
    state: started

- name: Write site configuration
  template:
    src: nginx-site.conf
    dest: /etc/nginx/sites-enabled/tunnel
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart nginx
