version: "3"
services:
  riemann:
    build:
      context: riemann
    restart: on-failure
    hostname: monitor
    links:
      - influx
    volumes:
      - ./riemann/riemann.config:/riemann/etc/riemann.config:ro
    environment:
      - EXTRA_CLASSPATH=/riemann/etc
      - INFLUXDB_HOST=influx
      - INFLUXDB_DB=merkledb
    ports:
      - "5555:5555/udp"
      - "5555:5555"
      - "5556:5556"

  riemann-dash:
    image: rlister/riemann-dash
    restart: on-failure
    depends_on:
      - riemann
    volumes:
      - ./data/riemann/config:/app/config
    environment:
      - WS_CONFIG=/app/config/dashboards.json
    ports:
      - "4567:4567"

  influx:
    image: influxdb:1.7-alpine
    restart: on-failure
    volumes:
      - ./data/influx:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=merkledb
    ports:
      - "8086:8086"
    command: -config /etc/influxdb/influxdb.conf

  grafana:
    build:
      context: grafana
    restart: on-failure
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - influx
    ports:
      - "3000:3000"
